# Multi container example

apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  containers:
    - name: nginx
      image: docker.io/nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
    - name: mongo
      image: docker.io/mongo
      resources:
        limits: 
          memory: "128Mi"
          cpu: "500m"
 