apiVersion: v1
kind: Pod
metadata:
  name: nginx-04
  labels:
    app: nginx
    example: service
spec:
  containers:
    - name: nginx
      image: docker.io/nginx

---

apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  selector:
    app: nginx
  ports:
    - protocal: TCP
      port: 80
      targetPort: 1234
