apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-frontend
data:
  CATALOGUE_HOST: catalogue-ip
  CATALOGUE_PORT: catalogue-port
  USER_HOST: user-host
  USER_PORT: user-port
  CART_HOST: cart-host
  CART_PORT: cart-port
  SHIPPING_HOST: shipping-host
  SHIPPING_PORT: shipping-port
  PAYMENT_HOST: payment-host
  PAYMENT_PORT: payment-port

