apiVersion: v1
kind: Pod
metadata:
  name: nginx-sg-tst
  namespace: backend
  labels:
    app: api
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
    - name: nginx-sg-tst
      image: docket.io/nginx 