apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-all-network
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: api
  policyTypes:
  - Ingress
  - Egress
