apiVersion: v1
kind: Namespace
metadata:
  name: pod-sec-policy
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: deployment
metadata:
  name: test-psp
  namespace: Pod-Sec-Policy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
  spec:
    containers:
      - name: nginx
        image: docker.io/nginx