apiVersion: v1
kind: Namespace
metadata:
  name: pod-sec-policy
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: policy/v1
kind: PodSecurityPolicy
metadata:
  name: test-psp
spec:
  privileged: false
  volumes:
    - 'configMap'
    - 'secret'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  seLinux:
    rule: 'RunAsAny'
  runAsUser:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'

---
apiVersion: v1
kind: deployment
metadata:
  name: test-psp
  namespace: pod-sec-policy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
  spec:
    containers:
      - name: nginx
        image: docker.io/nginx