apiVersion: v1
kind: ServiceAccount
metadata:
  name: debug
  namespace: default

---
apiVersion: v1
kind: Pod
metadata: 
  name: debug
  namespace: default
spec:
  serviceAccountName: debug
  containers:
    - name: debug
      image: rkalluru/debug
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: defauld-ns-pod-reder
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: defauld-ns-pod-reder-debug-pod
subjects:
  - kind: ServiceAccount
    name: debug
    namespace: default 
roleRef:
  kind: Role
  name: defauld-ns-pod-reder
  apiGroup: rbac.authorization.k8s.io